### ISSUE TITLE
I compiled gsuneido, from where can i take an initial suneido.db?

### ISSUE THREAD

**Issue by neimanpinchas** [apmckinlay/gsuneido#19]
I compiled gsuneido, from where can i take an initial suneido.db?

**Comment by apmckinlay** [comment]
You can use the latest Github Release which contains a suneido.db
[](https://github.com/apmckinlay/gsuneido/releases/tag/2022-03-04)

**Comment by neimanpinchas** [comment]
https://github.com/apmckinlay/gsuneido/releases
