### ISSUE TITLE
Cross platform UI

### ISSUE THREAD

**Issue by neimanpinchas** [apmckinlay/gsuneido#25]
Hi

Wondering if there are any plans to use a cross platform UI instead of the windows GUI e. g. https://github.com/therecipe/qt

My interest in it is linux support

For some reason wine is crashing with an access violation, I am not equipped to figure it out using the binary stackstarce

**Comment by apmckinlay** [comment]
We have a browser based front end. (Not released yet.)
However, so far we have not implemented the IDE, just applications.
One of the reasons for that is that we use Scintilla for the code editor.
We use Code Mirror for the browser front end but it's quite different.

Other people have tried Wine, with varying success.
I don't know what the issues were.

Thanks for the interest.
